spring.application.name=quiz-leaderboard
server.port=8080

quiz.api.base-url=https://devapigw.vidalhealthtpa.com/srm-quiz-task
quiz.api.reg-no=RA2311003030424
quiz.api.total-polls=10
quiz.api.poll-delay-ms=5000
quiz.api.connect-timeout-ms=10000
quiz.api.read-timeout-ms=15000

logging.level.com.srm.quiz=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
